spring:
  application:
    name: client-provider
  profiles:
    active: dev
db:
  host: ec2-79-125-26-232.eu-west-1.compute.amazonaws.com
  port: 5432
  database: dcdiau51fbv8lp
  username: rqesrgpikegrba
  password: aef0a8af3cf50fd9e3afe9444f6a190126802b20e1d2771cd28413cfa7c34f5e
kafka:
  properties:
    "[bootstrap.servers]": moped-01.srvs.cloudkafka.com:9094,moped-02.srvs.cloudkafka.com:9094,moped-03.srvs.cloudkafka.com:9094
    "[sasl.jaas.config]": org.apache.kafka.common.security.scram.ScramLoginModule required username="2z2j7jw9" password="gGBcXuQW6peGnHhInj9TE09n_d4IadbE";
    "[client.id]": 2z2j7jw9-producer
    "[acks]": all
    "[delivery.timeout.ms]": 90000
    "[enable.idempotence]": true
    "[batch.size]": 10240
    "[linger.ms]": 100
    "[security.protocol]": SASL_SSL
    "[sasl.mechanism]": SCRAM-SHA-256
